export const OptionAsiste = {
  BtnCrearStickerAndUrl: true,
  BtnEditStickerAndUrl: false,
  BtnCrearNotaAndUrl: false,
  BtnEditNotaAndUrl: false,
  BtnCrearResultAndUrl: false,
  BtnEditResultAndUrl: false,
  MenuSetting: false,
  OrdersActive: true,
  OrdersInactive: false,
  Cerrarorden: false,
  ActivarOrden: false,
  UserConfigCreateAndUrl: false,
  UserConfigEditAnUrl: false,
  GroupConfigCreateAndUrl: true,
  GroupConfigEditAndUrl: true,
  ObservacionPredeCreateAndUrl: true,
  ObservacionPredeEditAndUrl: true,
  OptionCreateAndUrl: false,
  OptionEditAndUrl: false,
  NumberCreateAndUrl: false,
  NumberEditAndUrl: false,
};

export const OptionTecnichal = {
  BtnCrearStickerAndUrl: true,
  BtnEditStickerAndUrl: true,
  BtnCrearNotaAndUrl: true,
  BtnEditNotaAndUrl: true,
  BtnCrearResultAndUrl: true,
  BtnEditResultAndUrl: true,
  MenuSetting: true,
  OrdersActive: true,
  OrdersInactive: true,
  Cerrarorden: true,
  ActivarOrden: true,
  UserConfigCreateAndUrl: true,
  UserConfigEditAnUrl: true,
  GroupConfigCreateAndUrl: true,
  GroupConfigEditAndUrl: true,
  ObservacionPredeCreateAndUrl: true,
  ObservacionPredeEditAndUrl: true,
  OptionCreateAndUrl: true,
  OptionEditAndUrl: true,
  NumberCreateAndUrl: true,
  NumberEditAndUrl: true,
};

export const OptionConsult = {
  BtnCrearStickerAndUrl: false,
  BtnEditStickerAndUrl: false,
  BtnCrearNotaAndUrl: false,
  BtnEditNotaAndUrl: false,
  BtnCrearResultAndUrl: false,
  BtnEditResultAndUrl: false,
  MenuSetting: false,
  OrdersActive: true,
  OrdersInactive: false,
  Cerrarorden: false,
  ActivarOrden: false,
  UserConfigCreateAndUrl: false,
  UserConfigEditAnUrl: false,
  GroupConfigCreateAndUrl: false,
  GroupConfigEditAndUrl: false,
  ObservacionPredeCreateAndUrl: false,
  ObservacionPredeEditAndUrl: false,
  OptionCreateAndUrl: false,
  OptionEditAndUrl: false,
  NumberCreateAndUrl: false,
  NumberEditAndUrl: false,
};

export const OptionAdministrator = {
  BtnCrearStickerAndUrl: true,
  BtnEditStickerAndUrl: true,
  BtnCrearNotaAndUrl: true,
  BtnEditNotaAndUrl: true,
  BtnCrearResultAndUrl: true,
  BtnEditResultAndUrl: true,
  MenuSetting: true,
  OrdersActive: true,
  OrdersInactive: true,
  Cerrarorden: true,
  ActivarOrden: true,
  UserConfigCreateAndUrl: true,
  UserConfigEditAnUrl: true,
  GroupConfigCreateAndUrl: true,
  GroupConfigEditAndUrl: true,
  ObservacionPredeCreateAndUrl: true,
  ObservacionPredeEditAndUrl: true,
  OptionCreateAndUrl: true,
  OptionEditAndUrl: true,
  NumberCreateAndUrl: true,
  NumberEditAndUrl: true,
};

export const OptionDefault = {
  BtnCrearStickerAndUrl: false,
  BtnEditStickerAndUrl: false,
  BtnCrearNotaAndUrl: false,
  BtnEditNotaAndUrl: false,
  BtnCrearResultAndUrl: false,
  BtnEditResultAndUrl: false,
  MenuSetting: false,
  OrdersActive: true,
  OrdersInactive: false,
  Cerrarorden: false,
  ActivarOrden: false,
  UserConfigCreateAndUrl: false,
  UserConfigEditAnUrl: false,
  GroupConfigCreateAndUrl: false,
  GroupConfigEditAndUrl: false,
  ObservacionPredeCreateAndUrl: false,
  ObservacionPredeEditAndUrl: false,
  OptionCreateAndUrl: false,
  OptionEditAndUrl: false,
  NumberCreateAndUrl: false,
  NumberEditAndUrl: false,
};
